// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShowReel.Data;

#nullable disable

namespace ShowReel.Data.Migrations
{
    [DbContext(typeof(ShowReelDbContext))]
    [Migration("20220520191139_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("ReelSession", b =>
                {
                    b.Property<int>("ReelCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionCollectionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReelCollectionId", "SessionCollectionId");

                    b.HasIndex("SessionCollectionId");

                    b.ToTable("ReelSession");
                });

            modelBuilder.Entity("ShowReel.Core.Domain.Reel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoDefinition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoStandard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A factory is working on the new Bud Light Platinum.",
                            Duration = "00:00:30:12",
                            Name = "Bud Light",
                            VideoDefinition = "SD",
                            VideoStandard = "PAL"
                        },
                        new
                        {
                            Id = 2,
                            Description = "At a party, a brown shelled M&M is mistaken for being naked. As a result, the red M&M tears off its skin and dances to \"Sexy and I Know It\" by LMFAO.",
                            Duration = "00:00:15:27",
                            Name = "M&M's",
                            VideoDefinition = "SD",
                            VideoStandard = "NTSC"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A group of vampires are having a party in the woods. The vampire in charge of drinks (blood types) arrives in his Audi. The bright lights of the car kills all of the vampires, with him wondering where everyone went afterwards.",
                            Duration = "00:01:30:00",
                            Name = "Audi",
                            VideoDefinition = "SD",
                            VideoStandard = "PAL"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Clint Eastwood recounts how the automotive industry survived the Great Recession.",
                            Duration = "00:00:10:14",
                            Name = "Chrysler",
                            VideoDefinition = "SD",
                            VideoStandard = "PAL"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A man walks through a street to discover a beautiful woman (Catrinel Menghia) standing on a parking space, who proceeds to approach and seduce him, when successfully doing so he then discovers he was about to kiss a Fiat 500 Abarth.",
                            Duration = "00:00:18:11",
                            Name = "Fiat",
                            VideoDefinition = "SD",
                            VideoStandard = "NTSC"
                        },
                        new
                        {
                            Id = 6,
                            Description = "People in the Middles Ages try to entertain their king (Elton John) for a Pepsi. While the first person fails, a mysterious person (Season 1 X Factor winner Melanie Amaro) wins the Pepsi by singing Aretha Franklin's \"Respect\".\" After she wins, she overthrows the king and gives Pepsi to all the town.",
                            Duration = "00:00:20:00",
                            Name = "Pepsi",
                            VideoDefinition = "SD",
                            VideoStandard = "NTSC"
                        },
                        new
                        {
                            Id = 7,
                            Description = "An ad featuring the creators of the camera phone, Siri, and the first text message. The creators of Words with Friends also appear parodying the incident involving Alec Baldwin playing the game on an airplane.",
                            Duration = "00:00:10:05",
                            Name = "Best Buy",
                            VideoDefinition = "HD",
                            VideoStandard = "PAL"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Video Promo",
                            Duration = "00:00:20:10",
                            Name = "Captain America The First Avenger",
                            VideoDefinition = "HD",
                            VideoStandard = "PAL"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A computer generated black beetle runs fast, as it is referencing the new,Volkswagen model",
                            Duration = "00:00:30:00",
                            Name = "Volkswagen \"Black Beetle\"",
                            VideoDefinition = "HD",
                            VideoStandard = "NTSC"
                        });
                });

            modelBuilder.Entity("ShowReel.Core.Domain.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("ReelSession", b =>
                {
                    b.HasOne("ShowReel.Core.Domain.Reel", null)
                        .WithMany()
                        .HasForeignKey("ReelCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShowReel.Core.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
